# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apperta Foundation CIC
email: info@apperta.org
description: > # this means to ignore newlines until "baseurl:"
 The Apperta Foundation is a clinician-led, not-for-profit company. Supported by NHS England, NHS Digital and others, we promote open systems and standards for digital health and social care. We show how the delivery of health and social care can be transformed when data, information and knowledge in IT systems is open, shareable and computable.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://appertafoundation.github.io/" # the base hostname & protocol for your site
twitter_username: AppertaUK
github_username:  Apperta

collections:
  - subcommittees
  - directors
  - members
  - products
  - keydocuments

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

